### ISSUE TITLE
Icon upload fails to update on first try

### ISSUE THREAD

**Issue by jickpictures** [GunnJerkens/gj-maps#18]
On creating a new category and uploading an icon on the first try -- the icon does not update into the category. Debugging provides this notice:

`Undefined index: icon in /Users/graphics/RyanGordon/Web/gj-maps/public/content/plugins/gj-maps/db/gj-maps-db-class.php on line 417`

Any additional editing of an existing category after the first time will allow an icon to be updated/uploaded.

**Comment by shampine** [comment]
I looked at this, we aren't looking at the multipart upload on new items. So it is just skipped right over.

Fix A) Disable the image upload button on new item

Fix B) Add a static method to do the file uploading in the DB class that can be used multiple places

B is the better solution. But A is an ok bandaid.
