### ISSUE TITLE
Foreign key index error when deleting a category

### ISSUE THREAD

**Issue by shampine** [GunnJerkens/gj-maps#26]
Need to provide a better error handling solution when attempting to deleting a category or delete all POI or unlink all POI when deleting a category.

Should POI be deleted? Dropped back to a 'default' category? Or an error message returned?

**Comment by guitarbeard** [comment]
I think we should let the user decide with some sort of warning dialog that gives them the options to:
1. delete all related POI
2. set all related POI to Default category
3. cancel delete

**Comment by shampine** [comment]
Maybe do this in a modal popup with all three choices?

**Comment by joesgit** [comment]
Just a suggestion - maybe you can append a "1" or something to "Default" if a "Default" category already exists.

**Comment by guitarbeard** [comment]
Or, what if instead of making a new "Default1" category, I just check if one exists and set it to that one.
