### ISSUE TITLE
Need solution for the absolute urls in the database

### ISSUE THREAD

**Issue by shampine** [GunnJerkens/gj-maps#39]
We use absolute URLs in the database making them non portable, either:

A) Switch to relative URLs and append the hostname for the API response
B) Keep the absolute URLs and verify that their hostname matches the server's hostname

**Comment by guitarbeard** [comment]
Is the icon the only place where absolute urls exist?
I think we should use relative URLs, otherwise our local dev environment will not match the data downloaded from production.

**Comment by shampine** [comment]
The only place we need absolute URLs is for the API layer. You can instantiate a map with data from another WordPress instance.

**Comment by shampine** [comment]
I'd vote to set the to relative, we probably need to code in a fallback for existing sites or a migration to rewrite that column. I hadn't yet thought out what a database migration strategy would be, that's one reason why we have the "legacy/static" branch.
