### ISSUE TITLE
Undefined index error on map name change

### ISSUE THREAD

**Issue by chazbeaner** [GunnJerkens/gj-maps#49]
Looks like there are multiple updates/changes happening to the plugin at this very moment and downloading/updating from an hour ago to five minutes ago already fixed some of the issues, but this one persists when trying to change the map name:

`Undefined index: id in /gj-maps-master/inc/gj-maps-db-class.php on line 275`

**Comment by shampine** [comment]
Should be fixed now. Can you confirm for me?

**Comment by shampine** [comment]
I'm rolling through and testing everything at the moment and pushing fixes to master. I needed to roll in the latest 1.0.0 branch as it fixed a ton of super important sql issues in the db class, on the reverse of that though I rewrote almost the entirety of the admin/db classes which means a lot of bugs possibly exist. 

Feel free to open any other tickets for any bugs you find, I have a few I'm about to open shortly that aren't super critical to fixing today.

**Comment by chazbeaner** [comment]
Sounds good. Confirmed that map name change bug fixed, so this can be marked resolved. If I come across anything else, I'll def open an issue.

**Comment by shampine** [comment]
Awesome, feel free to open any issues you see needed. If so inclined also feel free to send any pull requests. I'm pushing this towards a stable 1.0.0 release and possibly to put it up on WordPress.org. Currently though it's always been in limbo for us and a forever beta plugin.
