### ISSUE TITLE
Undefined method on category edit

### ISSUE THREAD

**Issue by chazbeaner** [GunnJerkens/gj-maps#51]
Fatal error:

`Call to undefined method gjMapsDB::editCat() in /gj-maps-master/inc/gj-maps-admin-class.php on line 410`

**Comment by shampine** [comment]
Pushed a possible fix on master, let me know if that resolves it.

**Comment by chazbeaner** [comment]
(Sorry for the delay)

Looks like it fixed that one issue and unearthed a bunch more:

`'Warning: Illegal string offset 'icon' in /gj-maps-master/inc/gj-maps-db-class.php on line 553'`

`Warning: Illegal string offset 'id' in /gj-maps-master/inc/gj-maps-db-class.php on line 554`

`Warning: Illegal string offset 'map_id' in /gj-maps-master/inc/gj-maps-db-class.php on line 554`

`Notice: Undefined index: map_id in /gj-maps-master/admin/gj-maps-categories.php on line 94`

**Comment by shampine** [comment]
I think I just pushed a fix up that will square this one away as well. Thanks for getting back to the thread, no worry on the delay.

**Comment by chazbeaner** [comment]
Ok, the errors are all gone, but there's something happening with the category icon. Icon uploads and shows but does not appear on the map. If you update the Categories (seems to be related to changing the Hide and Resist checkboxes), then the icon disappears. I haven't quite nailed down the specific combination that causes the icon to disappear, but I'll let you know if I do.

**Comment by shampine** [comment]
I'll see if I can recreate it, this is also related to issue #18 in which when you create a category the icon doesn't upload.

**Comment by shampine** [comment]
Pushed an update, it was my logic to set the icon to an empty string if it doesn't have one.. which was incorrect.

**Comment by chazbeaner** [comment]
Would you rather new Issues be opened related to the icons?

**Comment by shampine** [comment]
Let's go ahead and do that. I'm going to close this issue as it is now unrelated.
